require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DestroyeHistoriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DestroyeHistory. As you add validations to DestroyeHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DestroyeHistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all destroye_histories as @destroye_histories" do
      destroye_history = DestroyeHistory.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:destroye_histories)).to eq([destroye_history])
    end
  end

  describe "GET show" do
    it "assigns the requested destroye_history as @destroye_history" do
      destroye_history = DestroyeHistory.create! valid_attributes
      get :show, {:id => destroye_history.to_param}, valid_session
      expect(assigns(:destroye_history)).to eq(destroye_history)
    end
  end

  describe "GET new" do
    it "assigns a new destroye_history as @destroye_history" do
      get :new, {}, valid_session
      expect(assigns(:destroye_history)).to be_a_new(DestroyeHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested destroye_history as @destroye_history" do
      destroye_history = DestroyeHistory.create! valid_attributes
      get :edit, {:id => destroye_history.to_param}, valid_session
      expect(assigns(:destroye_history)).to eq(destroye_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DestroyeHistory" do
        expect {
          post :create, {:destroye_history => valid_attributes}, valid_session
        }.to change(DestroyeHistory, :count).by(1)
      end

      it "assigns a newly created destroye_history as @destroye_history" do
        post :create, {:destroye_history => valid_attributes}, valid_session
        expect(assigns(:destroye_history)).to be_a(DestroyeHistory)
        expect(assigns(:destroye_history)).to be_persisted
      end

      it "redirects to the created destroye_history" do
        post :create, {:destroye_history => valid_attributes}, valid_session
        expect(response).to redirect_to(DestroyeHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved destroye_history as @destroye_history" do
        post :create, {:destroye_history => invalid_attributes}, valid_session
        expect(assigns(:destroye_history)).to be_a_new(DestroyeHistory)
      end

      it "re-renders the 'new' template" do
        post :create, {:destroye_history => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested destroye_history" do
        destroye_history = DestroyeHistory.create! valid_attributes
        put :update, {:id => destroye_history.to_param, :destroye_history => new_attributes}, valid_session
        destroye_history.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested destroye_history as @destroye_history" do
        destroye_history = DestroyeHistory.create! valid_attributes
        put :update, {:id => destroye_history.to_param, :destroye_history => valid_attributes}, valid_session
        expect(assigns(:destroye_history)).to eq(destroye_history)
      end

      it "redirects to the destroye_history" do
        destroye_history = DestroyeHistory.create! valid_attributes
        put :update, {:id => destroye_history.to_param, :destroye_history => valid_attributes}, valid_session
        expect(response).to redirect_to(destroye_history)
      end
    end

    describe "with invalid params" do
      it "assigns the destroye_history as @destroye_history" do
        destroye_history = DestroyeHistory.create! valid_attributes
        put :update, {:id => destroye_history.to_param, :destroye_history => invalid_attributes}, valid_session
        expect(assigns(:destroye_history)).to eq(destroye_history)
      end

      it "re-renders the 'edit' template" do
        destroye_history = DestroyeHistory.create! valid_attributes
        put :update, {:id => destroye_history.to_param, :destroye_history => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested destroye_history" do
      destroye_history = DestroyeHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => destroye_history.to_param}, valid_session
      }.to change(DestroyeHistory, :count).by(-1)
    end

    it "redirects to the destroye_histories list" do
      destroye_history = DestroyeHistory.create! valid_attributes
      delete :destroy, {:id => destroye_history.to_param}, valid_session
      expect(response).to redirect_to(destroye_histories_url)
    end
  end

end
